const niches = {
  realEstate: {
    id: 'realEstate',
    label: 'Real Estate',
    description: 'Properties, site visits and closings',
    icon: 'home',
    color: '#8B5CF6',
    terminology: {
      lead: 'Prospect',
      leads: 'Prospects',
      deal: 'Property',
      deals: 'Properties',
      customer: 'Client',
      customers: 'Clients',
      pipeline: 'Property Pipeline',
      value: 'Property Value',
      closed: 'Sold',
    },
    pipelineStages: [
      { id: 'newLead',        label: 'New Lead',              color: '#6B7280', emoji: '🆕' },
      { id: 'contacted',      label: 'Contacted',             color: '#3B82F6', emoji: '📞' },
      { id: 'visitScheduled', label: 'Visit Scheduled',       color: '#8B5CF6', emoji: '📅' },
      { id: 'visitDone',      label: 'Visit Done',            color: '#F59E0B', emoji: '🏠' },
      { id: 'negotiation',    label: 'Negotiation',           color: '#F97316', emoji: '🤝' },
      { id: 'tokenPaid',      label: 'Booking / Token Paid',  color: '#10B981', emoji: '💰' },
      { id: 'closed',         label: 'Closed — Won',          color: '#22C55E', emoji: '✅' },
      { id: 'lost',           label: 'Closed — Lost',         color: '#EF4444', emoji: '❌' },
    ],
    leadFields: [
      { key: 'propertyType',   label: 'Property Interested In', type: 'select',   options: ['Residential Flat', 'Villa', 'Plot', 'Commercial', 'Rental', 'Other'] },
      { key: 'budget',         label: 'Budget (₹)',              type: 'text',     placeholder: 'e.g. 75,00,000' },
      { key: 'location',       label: 'Preferred Location',      type: 'text',     placeholder: 'e.g. Sector 17, Chandigarh' },
      { key: 'bhk',            label: 'BHK Requirement',         type: 'select',   options: ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '5+ BHK', 'Villa', 'Not decided'] },
      { key: 'source',         label: 'Lead Source',             type: 'select',   options: ['Facebook Ads', 'Google Ads', 'Instagram', 'Referral', 'Walk-in', 'Website', 'Housing.com', 'MagicBricks', 'Other'] },
      { key: 'timeline',       label: 'Purchase Timeline',       type: 'select',   options: ['Immediate (0-1 month)', '1-3 months', '3-6 months', '6+ months', 'Just exploring'] },
      { key: 'loanRequired',   label: 'Loan Required',           type: 'select',   options: ['Yes', 'No', 'Pre-approved', 'Maybe'] },
      { key: 'followUpDate',   label: 'Follow-up Date',          type: 'date' },
      { key: 'notes',          label: 'Notes',                   type: 'textarea', placeholder: 'Any specific requirements, objections, or key points...' },
    ],
    hotLeadCriteria: 'High budget, immediate timeline, visited site, pre-approved loan',
    kpis: [
      { key: 'totalLeads',     label: 'Total Prospects',    icon: 'users'    },
      { key: 'hotLeads',       label: 'Hot Prospects',      icon: 'fire'     },
      { key: 'pipelineValue',  label: 'Pipeline Value',     icon: 'rupee'    },
      { key: 'closedMonth',    label: 'Closed This Month',  icon: 'check'    },
    ],
    aiPromptContext: 'real estate agency in India. Prospects are property buyers. They deal with residential flats, villas, plots and commercial spaces. Important factors: budget, location preference, BHK requirement, loan eligibility, site visit feedback.',
    whatsappTemplate: 'Hi {name}, this is regarding the property you enquired about. Are you still looking for {propertyType} in {location} within budget of {budget}? Would love to schedule a site visit at your convenience.',
  },

  saas: {
    id: 'saas',
    label: 'SaaS / Tech',
    description: 'Trials, demos and MRR growth',
    icon: 'monitor',
    color: '#3B82F6',
    terminology: {
      lead: 'Lead',
      leads: 'Leads',
      deal: 'Deal',
      deals: 'Deals',
      customer: 'Customer',
      customers: 'Customers',
      pipeline: 'Sales Pipeline',
      value: 'MRR / Deal Value',
      closed: 'Converted',
    },
    pipelineStages: [
      { id: 'newLead',     label: 'New Lead',        color: '#6B7280', emoji: '🆕' },
      { id: 'contacted',   label: 'Contacted',       color: '#3B82F6', emoji: '📧' },
      { id: 'qualified',   label: 'Qualified',       color: '#8B5CF6', emoji: '✔️' },
      { id: 'trial',       label: 'Trial Started',   color: '#F59E0B', emoji: '🧪' },
      { id: 'demo',        label: 'Demo Done',       color: '#F97316', emoji: '🖥️' },
      { id: 'proposal',    label: 'Proposal Sent',   color: '#10B981', emoji: '📋' },
      { id: 'closed',      label: 'Closed — Won',    color: '#22C55E', emoji: '✅' },
      { id: 'lost',        label: 'Closed — Lost',   color: '#EF4444', emoji: '❌' },
    ],
    leadFields: [
      { key: 'companyName',    label: 'Company Name',        type: 'text',     placeholder: 'e.g. Acme Corp' },
      { key: 'companySize',    label: 'Company Size',        type: 'select',   options: ['1-10', '11-50', '51-200', '201-500', '500+'] },
      { key: 'useCase',        label: 'Use Case / Pain Point', type: 'text',   placeholder: 'What problem are they solving?' },
      { key: 'mrr',            label: 'Potential MRR (₹)',    type: 'text',    placeholder: 'e.g. 15000' },
      { key: 'source',         label: 'Lead Source',          type: 'select',  options: ['LinkedIn', 'Google Ads', 'Product Hunt', 'Referral', 'Cold Email', 'Inbound', 'Conference', 'Other'] },
      { key: 'decisionMaker',  label: 'Decision Maker',       type: 'text',    placeholder: 'Name and title' },
      { key: 'currentTool',    label: 'Currently Using',      type: 'text',    placeholder: 'Competitor or alternative' },
      { key: 'trialEndDate',   label: 'Trial End Date',       type: 'date' },
      { key: 'followUpDate',   label: 'Follow-up Date',       type: 'date' },
      { key: 'notes',          label: 'Notes',                type: 'textarea', placeholder: 'Key objections, requirements, next steps...' },
    ],
    hotLeadCriteria: 'Active trial, decision maker engaged, clear use case, budget confirmed',
    kpis: [
      { key: 'totalLeads',    label: 'Total Leads',      icon: 'users'    },
      { key: 'hotLeads',      label: 'Hot Leads',        icon: 'fire'     },
      { key: 'pipelineMRR',   label: 'Pipeline MRR',     icon: 'rupee'    },
      { key: 'closedMonth',   label: 'Won This Month',   icon: 'check'    },
    ],
    aiPromptContext: 'B2B SaaS company. Leads are businesses evaluating software. Key factors: company size, use case fit, trial engagement, decision maker access, budget and timeline.',
    whatsappTemplate: 'Hi {name}, following up on your trial of our platform. Have you had a chance to explore {useCase}? Would love to schedule a quick demo call this week.',
  },

  healthcare: {
    id: 'healthcare',
    label: 'Healthcare',
    description: 'Patients, appointments and care',
    icon: 'heart',
    color: '#EF4444',
    terminology: {
      lead: 'Patient',
      leads: 'Patients',
      deal: 'Treatment',
      deals: 'Treatments',
      customer: 'Patient',
      customers: 'Patients',
      pipeline: 'Patient Pipeline',
      value: 'Treatment Value',
      closed: 'Treated',
    },
    pipelineStages: [
      { id: 'inquiry',       label: 'Inquiry',          color: '#6B7280', emoji: '📋' },
      { id: 'contacted',     label: 'Contacted',        color: '#3B82F6', emoji: '📞' },
      { id: 'appointment',   label: 'Appointment Set',  color: '#8B5CF6', emoji: '📅' },
      { id: 'consultation',  label: 'Consultation',     color: '#F59E0B', emoji: '🩺' },
      { id: 'treatment',     label: 'Under Treatment',  color: '#F97316', emoji: '💊' },
      { id: 'followUp',      label: 'Follow-up',        color: '#10B981', emoji: '🔄' },
      { id: 'closed',        label: 'Discharged',       color: '#22C55E', emoji: '✅' },
      { id: 'lost',          label: 'Dropped',          color: '#EF4444', emoji: '❌' },
    ],
    leadFields: [
      { key: 'condition',    label: 'Condition / Concern',   type: 'text',    placeholder: 'e.g. Back pain, Diabetes management' },
      { key: 'age',          label: 'Age',                   type: 'text',    placeholder: 'Patient age' },
      { key: 'gender',       label: 'Gender',                type: 'select',  options: ['Male', 'Female', 'Other', 'Prefer not to say'] },
      { key: 'insurance',    label: 'Insurance Provider',    type: 'text',    placeholder: 'e.g. Star Health, No Insurance' },
      { key: 'source',       label: 'Referred By',           type: 'select',  options: ['Google', 'Facebook', 'Doctor Referral', 'Patient Referral', 'Walk-in', 'Hospital Website', 'Other'] },
      { key: 'lastVisit',    label: 'Last Visit Date',       type: 'date' },
      { key: 'followUpDate', label: 'Next Appointment',      type: 'date' },
      { key: 'notes',        label: 'Clinical Notes',        type: 'textarea', placeholder: 'Symptoms, history, treatment notes...' },
    ],
    hotLeadCriteria: 'Urgent condition, confirmed appointment, good insurance coverage',
    kpis: [
      { key: 'totalLeads',     label: 'Total Patients',     icon: 'users'    },
      { key: 'hotLeads',       label: 'Urgent Cases',       icon: 'fire'     },
      { key: 'pipelineValue',  label: 'Treatment Value',    icon: 'rupee'    },
      { key: 'closedMonth',    label: 'Treated This Month', icon: 'check'    },
    ],
    aiPromptContext: 'healthcare clinic or hospital. Patients are seeking medical care. Key factors: condition severity, appointment scheduling, treatment follow-up, insurance coverage.',
    whatsappTemplate: 'Hi {name}, this is a reminder for your appointment on {followUpDate}. Please bring your previous reports and insurance card. Looking forward to seeing you.',
  },

  education: {
    id: 'education',
    label: 'Education',
    description: 'Students, enrolments and courses',
    icon: 'book',
    color: '#10B981',
    terminology: {
      lead: 'Student',
      leads: 'Students',
      deal: 'Enrolment',
      deals: 'Enrolments',
      customer: 'Student',
      customers: 'Students',
      pipeline: 'Admissions Pipeline',
      value: 'Course Fee',
      closed: 'Enrolled',
    },
    pipelineStages: [
      { id: 'inquiry',      label: 'Inquiry',          color: '#6B7280', emoji: '📋' },
      { id: 'contacted',    label: 'Contacted',        color: '#3B82F6', emoji: '📞' },
      { id: 'demoClass',    label: 'Demo Class',       color: '#8B5CF6', emoji: '🎓' },
      { id: 'counselling',  label: 'Counselling',      color: '#F59E0B', emoji: '💬' },
      { id: 'feeDiscussed', label: 'Fee Discussed',    color: '#F97316', emoji: '💰' },
      { id: 'enrolled',     label: 'Enrolled',         color: '#10B981', emoji: '✅' },
      { id: 'active',       label: 'Active Student',   color: '#22C55E', emoji: '📚' },
      { id: 'lost',         label: 'Dropped / Lost',   color: '#EF4444', emoji: '❌' },
    ],
    leadFields: [
      { key: 'courseInterest', label: 'Course Interested In', type: 'text',    placeholder: 'e.g. Full Stack Dev, MBA, IELTS' },
      { key: 'educationLevel', label: 'Current Education',    type: 'select',  options: ['10th', '12th', 'Graduation', 'Post Graduation', 'Working Professional'] },
      { key: 'budget',         label: 'Budget (₹)',           type: 'text',    placeholder: 'Course fee budget' },
      { key: 'source',         label: 'Lead Source',          type: 'select',  options: ['Facebook Ads', 'Google Ads', 'Instagram', 'Referral', 'Walk-in', 'Website', 'YouTube', 'Other'] },
      { key: 'schedule',       label: 'Preferred Schedule',   type: 'select',  options: ['Morning (8-12)', 'Afternoon (12-4)', 'Evening (4-8)', 'Weekend', 'Online / Self-paced'] },
      { key: 'parentName',     label: 'Parent / Guardian',    type: 'text',    placeholder: 'If applicable' },
      { key: 'followUpDate',   label: 'Follow-up Date',       type: 'date' },
      { key: 'notes',          label: 'Notes',                type: 'textarea', placeholder: 'Goals, concerns, financial situation...' },
    ],
    hotLeadCriteria: 'Attended demo class, clear budget, immediate start date, parent engaged',
    kpis: [
      { key: 'totalLeads',    label: 'Total Inquiries',    icon: 'users'    },
      { key: 'hotLeads',      label: 'Hot Students',       icon: 'fire'     },
      { key: 'pipelineValue', label: 'Fee Pipeline',       icon: 'rupee'    },
      { key: 'closedMonth',   label: 'Enrolled This Month', icon: 'check'   },
    ],
    aiPromptContext: 'education institute or coaching center. Students are prospective learners. Key factors: course fit, demo class attendance, fee budget, schedule preference, parental involvement.',
    whatsappTemplate: 'Hi {name}, thanks for your interest in {courseInterest}. We have a free demo class coming up this week. Would you like to attend? It will help you understand the course better.',
  },

  freelance: {
    id: 'freelance',
    label: 'Freelance / Agency',
    description: 'Projects, proposals and clients',
    icon: 'briefcase',
    color: '#F59E0B',
    terminology: {
      lead: 'Lead',
      leads: 'Leads',
      deal: 'Project',
      deals: 'Projects',
      customer: 'Client',
      customers: 'Clients',
      pipeline: 'Project Pipeline',
      value: 'Project Value',
      closed: 'Contracted',
    },
    pipelineStages: [
      { id: 'inquiry',    label: 'Inquiry',           color: '#6B7280', emoji: '📋' },
      { id: 'contacted',  label: 'Contacted',         color: '#3B82F6', emoji: '📧' },
      { id: 'scoping',    label: 'Scoping Call',      color: '#8B5CF6', emoji: '🔍' },
      { id: 'proposal',   label: 'Proposal Sent',     color: '#F59E0B', emoji: '📄' },
      { id: 'negotiation',label: 'Negotiation',       color: '#F97316', emoji: '🤝' },
      { id: 'contract',   label: 'Contract Signed',   color: '#10B981', emoji: '✍️' },
      { id: 'closed',     label: 'Project Active',    color: '#22C55E', emoji: '✅' },
      { id: 'lost',       label: 'Lost',              color: '#EF4444', emoji: '❌' },
    ],
    leadFields: [
      { key: 'projectType',  label: 'Project Type',      type: 'text',    placeholder: 'e.g. React website, Logo design, SEO' },
      { key: 'budget',       label: 'Budget (₹)',         type: 'text',    placeholder: 'Client budget range' },
      { key: 'timeline',     label: 'Project Timeline',   type: 'select',  options: ['< 1 week', '1-2 weeks', '2-4 weeks', '1-2 months', '2-3 months', '3+ months'] },
      { key: 'source',       label: 'Lead Source',        type: 'select',  options: ['Upwork', 'Fiverr', 'LinkedIn', 'Referral', 'Cold DM', 'Website', 'Instagram', 'Direct', 'Other'] },
      { key: 'techStack',    label: 'Tech / Tools Needed', type: 'text',  placeholder: 'e.g. React, Figma, WordPress' },
      { key: 'decisionMaker', label: 'Point of Contact',  type: 'text',   placeholder: 'Name and role' },
      { key: 'followUpDate', label: 'Follow-up Date',      type: 'date' },
      { key: 'notes',        label: 'Notes',               type: 'textarea', placeholder: 'Project requirements, client style, red flags...' },
    ],
    hotLeadCriteria: 'Clear scope, confirmed budget, urgent timeline, decision maker contacted',
    kpis: [
      { key: 'totalLeads',    label: 'Active Leads',     icon: 'users'    },
      { key: 'hotLeads',      label: 'Hot Leads',        icon: 'fire'     },
      { key: 'pipelineValue', label: 'Pipeline Value',   icon: 'rupee'    },
      { key: 'closedMonth',   label: 'Won This Month',   icon: 'check'    },
    ],
    aiPromptContext: 'freelancer or digital agency. Clients need project work. Key factors: project clarity, budget confirmation, timeline fit, contract signing, scope creep prevention.',
    whatsappTemplate: 'Hi {name}, thanks for reaching out about {projectType}. I have reviewed your requirements and would love to discuss the scope and timeline. Are you free for a 15-minute call this week?',
  },

  finance: {
    id: 'finance',
    label: 'Finance / Insurance',
    description: 'Policies, premiums and renewals',
    icon: 'dollar',
    color: '#06B6D4',
    terminology: {
      lead: 'Lead',
      leads: 'Leads',
      deal: 'Policy',
      deals: 'Policies',
      customer: 'Client',
      customers: 'Clients',
      pipeline: 'Policy Pipeline',
      value: 'Premium Value',
      closed: 'Policy Issued',
    },
    pipelineStages: [
      { id: 'newLead',    label: 'New Lead',          color: '#6B7280', emoji: '🆕' },
      { id: 'contacted',  label: 'Contacted',         color: '#3B82F6', emoji: '📞' },
      { id: 'qualified',  label: 'Needs Analysis',    color: '#8B5CF6', emoji: '📊' },
      { id: 'kyc',        label: 'KYC Submitted',     color: '#F59E0B', emoji: '📑' },
      { id: 'proposal',   label: 'Proposal Sent',     color: '#F97316', emoji: '📋' },
      { id: 'closed',     label: 'Policy Issued',     color: '#22C55E', emoji: '✅' },
      { id: 'renewal',    label: 'Renewal Due',       color: '#10B981', emoji: '🔄' },
      { id: 'lost',       label: 'Lapsed / Lost',     color: '#EF4444', emoji: '❌' },
    ],
    leadFields: [
      { key: 'policyType',     label: 'Policy Type',         type: 'select',  options: ['Term Life', 'Health Insurance', 'Motor Insurance', 'Investment / ULIP', 'Child Plan', 'Pension Plan', 'General Insurance', 'Other'] },
      { key: 'sumAssured',     label: 'Sum Assured (₹)',      type: 'text',    placeholder: 'e.g. 50,00,000' },
      { key: 'premium',        label: 'Annual Premium (₹)',   type: 'text',    placeholder: 'Expected premium' },
      { key: 'income',         label: 'Annual Income',        type: 'select',  options: ['< 3L', '3-5L', '5-10L', '10-20L', '20-50L', '50L+'] },
      { key: 'source',         label: 'Lead Source',          type: 'select',  options: ['Referral', 'Cold Call', 'LinkedIn', 'Facebook Ads', 'Google Ads', 'Walk-in', 'Other'] },
      { key: 'existingPolicy', label: 'Existing Policies',    type: 'text',    placeholder: 'Any existing coverage' },
      { key: 'renewalDate',    label: 'Renewal Date',         type: 'date' },
      { key: 'followUpDate',   label: 'Follow-up Date',       type: 'date' },
      { key: 'notes',          label: 'Notes',                type: 'textarea', placeholder: 'Financial goals, risk profile, family details...' },
    ],
    hotLeadCriteria: 'Clear need, confirmed income, no existing coverage, KYC ready',
    kpis: [
      { key: 'totalLeads',    label: 'Total Leads',      icon: 'users'    },
      { key: 'hotLeads',      label: 'Hot Leads',        icon: 'fire'     },
      { key: 'pipelineValue', label: 'Premium Pipeline', icon: 'rupee'    },
      { key: 'closedMonth',   label: 'Policies Issued',  icon: 'check'    },
    ],
    aiPromptContext: 'insurance agent or financial advisor in India. Clients need insurance or investment products. Key factors: income level, existing coverage gaps, risk appetite, nominee details, KYC completion.',
    whatsappTemplate: 'Hi {name}, following up on the {policyType} we discussed. Based on your profile, I have shortlisted 2-3 plans that offer great coverage within your budget. Can we connect for 15 minutes?',
  },

  retail: {
    id: 'retail',
    label: 'Retail / E-commerce',
    description: 'Customers, orders and repeat sales',
    icon: 'shopping',
    color: '#EC4899',
    terminology: {
      lead: 'Customer',
      leads: 'Customers',
      deal: 'Order',
      deals: 'Orders',
      customer: 'Customer',
      customers: 'Customers',
      pipeline: 'Customer Pipeline',
      value: 'Order Value',
      closed: 'Purchased',
    },
    pipelineStages: [
      { id: 'prospect',      label: 'Prospect',          color: '#6B7280', emoji: '👀' },
      { id: 'contacted',     label: 'Contacted',         color: '#3B82F6', emoji: '📞' },
      { id: 'interested',    label: 'Interested',        color: '#8B5CF6', emoji: '💭' },
      { id: 'quoteSent',     label: 'Quote Sent',        color: '#F59E0B', emoji: '📄' },
      { id: 'firstPurchase', label: 'First Purchase',    color: '#10B981', emoji: '🛍️' },
      { id: 'repeat',        label: 'Repeat Buyer',      color: '#22C55E', emoji: '✅' },
      { id: 'vip',           label: 'VIP Customer',      color: '#F97316', emoji: '⭐' },
      { id: 'churned',       label: 'Churned',           color: '#EF4444', emoji: '❌' },
    ],
    leadFields: [
      { key: 'productInterest', label: 'Product / Category',    type: 'text',    placeholder: 'e.g. Furniture, Electronics, Clothing' },
      { key: 'budget',          label: 'Budget (₹)',             type: 'text',    placeholder: 'Expected order value' },
      { key: 'location',        label: 'City / Location',        type: 'text',    placeholder: 'For delivery estimation' },
      { key: 'source',          label: 'Acquisition Source',     type: 'select',  options: ['Instagram', 'Facebook', 'Google', 'WhatsApp', 'Referral', 'Walk-in', 'Website', 'Amazon', 'Flipkart', 'Other'] },
      { key: 'lastPurchase',    label: 'Last Purchase Date',     type: 'date' },
      { key: 'avgOrderValue',   label: 'Avg Order Value (₹)',     type: 'text',    placeholder: 'Average spend per order' },
      { key: 'followUpDate',    label: 'Follow-up Date',         type: 'date' },
      { key: 'notes',           label: 'Notes',                  type: 'textarea', placeholder: 'Preferences, past orders, special requests...' },
    ],
    hotLeadCriteria: 'High intent, confirmed budget, fast decision, repeat buyer potential',
    kpis: [
      { key: 'totalLeads',    label: 'Total Customers',  icon: 'users'    },
      { key: 'hotLeads',      label: 'Hot Customers',    icon: 'fire'     },
      { key: 'pipelineValue', label: 'Pipeline Value',   icon: 'rupee'    },
      { key: 'closedMonth',   label: 'Orders This Month', icon: 'check'   },
    ],
    aiPromptContext: 'retail or e-commerce business. Customers are buyers of products. Key factors: product interest, budget, location for delivery, past purchase history, repeat potential.',
    whatsappTemplate: 'Hi {name}, thanks for your interest in {productInterest}. We have some great options within your budget. Can I send you a quick catalogue on WhatsApp?',
  },

  restaurant: {
    id: 'restaurant',
    label: 'Restaurant / Events',
    description: 'Bookings, events and reviews',
    icon: 'utensils',
    color: '#F97316',
    terminology: {
      lead: 'Inquiry',
      leads: 'Inquiries',
      deal: 'Booking',
      deals: 'Bookings',
      customer: 'Guest',
      customers: 'Guests',
      pipeline: 'Booking Pipeline',
      value: 'Event Value',
      closed: 'Confirmed',
    },
    pipelineStages: [
      { id: 'inquiry',      label: 'New Inquiry',       color: '#6B7280', emoji: '📋' },
      { id: 'contacted',    label: 'Contacted',         color: '#3B82F6', emoji: '📞' },
      { id: 'tasting',      label: 'Tasting Scheduled', color: '#8B5CF6', emoji: '🍽️' },
      { id: 'tastingDone',  label: 'Tasting Done',      color: '#F59E0B', emoji: '✔️' },
      { id: 'proposal',     label: 'Proposal Sent',     color: '#F97316', emoji: '📄' },
      { id: 'advance',      label: 'Advance Received',  color: '#10B981', emoji: '💰' },
      { id: 'closed',       label: 'Event Confirmed',   color: '#22C55E', emoji: '✅' },
      { id: 'lost',         label: 'Cancelled / Lost',  color: '#EF4444', emoji: '❌' },
    ],
    leadFields: [
      { key: 'eventType',    label: 'Event Type',          type: 'select',  options: ['Wedding', 'Reception', 'Engagement', 'Birthday', 'Anniversary', 'Corporate', 'Baby Shower', 'Other'] },
      { key: 'guestCount',   label: 'Expected Guests',      type: 'text',    placeholder: 'e.g. 150-200 guests' },
      { key: 'budget',       label: 'Budget (₹)',            type: 'text',    placeholder: 'Total event budget' },
      { key: 'eventDate',    label: 'Event Date',            type: 'date' },
      { key: 'venue',        label: 'Venue Preference',      type: 'text',    placeholder: 'e.g. Indoor hall, Outdoor garden' },
      { key: 'menuPref',     label: 'Menu Preference',       type: 'select',  options: ['Pure Veg', 'Non-Veg', 'Both', 'Jain', 'Custom'] },
      { key: 'source',       label: 'Referred By',           type: 'select',  options: ['Google', 'Instagram', 'Facebook', 'Referral', 'Walk-in', 'JustDial', 'Other'] },
      { key: 'followUpDate', label: 'Follow-up / Tasting Date', type: 'date' },
      { key: 'notes',        label: 'Notes',                 type: 'textarea', placeholder: 'Special requirements, dietary restrictions, decor requests...' },
    ],
    hotLeadCriteria: 'Confirmed date, adequate budget, completed tasting, advance paid',
    kpis: [
      { key: 'totalLeads',    label: 'Total Inquiries',  icon: 'users'    },
      { key: 'hotLeads',      label: 'Hot Inquiries',    icon: 'fire'     },
      { key: 'pipelineValue', label: 'Booking Value',    icon: 'rupee'    },
      { key: 'closedMonth',   label: 'Events This Month', icon: 'check'   },
    ],
    aiPromptContext: 'restaurant or event venue. Inquiries are for event bookings. Key factors: event type, guest count, budget, date availability, menu customization, advance payment.',
    whatsappTemplate: 'Hi {name}, thank you for your enquiry for {eventType} at our venue. We would love to host your event on {eventDate}. Can we schedule a tasting session and venue tour this week?',
  },
}

module.exports = niches